ingress:
  admin:
    annotations:
      kubernetes.io/ingress.class: nginx
    className: ''
    enabled: true
    hosts:
      - host: oauth.narratenet.com
        paths:
          - path: "/"
            pathType: ImplementationSpecific
    tls:
      - hosts:
          - oauth.narratenet.com
        secretName: narratenet-tls

  public:
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/configuration-snippet: |
        add_header X-Content-Type-Options nosniff;
        add_header "X-XSS-Protection" "1;mode=block";
        if ($http_origin ~* (^https?://([^/]+\.)*(api.narratenet.com|www.narratenet.com|narratenet.com|localhost:3000))) {
          add_header 'Access-Control-Allow-Origin' "$http_origin" always;
          add_header "Access-Control-Allow-Headers" "content-type, content-length, accept-encoding, x-csrf-token, authorization, accept, origin, cache-control, x-requested-with, access-control-allow-credentials, session-tracing-id, x-b3-spanid, x-b3-traceid, x-b3-sampled, tracing-api-key, enc-id-token, x-mfa-authorize-token, businessaccountfilter, businessdepositfilter, source, primaryaccounts, intent, x-mfa-action-id, inward-currency, if-none-match, content-disposition, more-transactions, x-mfa-transaction-id, x-mfa-transaction-type, x-mfa-otp, x-mfa-otp-ref-id" always;
          add_header "Access-Control-Allow-Credentials" "true" always;
          add_header "Access-Control-Allow-Methods" "POST, OPTIONS, GET, PUT, DELETE" always;
        }
        if ($request_method = 'OPTIONS') {
          add_header 'Access-Control-Allow-Origin' "$http_origin" always;
          add_header 'Access-Control-Allow-Credentials' 'true' always;
          add_header 'Access-Control-Allow-Methods' 'POST, OPTIONS, GET, PUT, DELETE' always;
          add_header 'Access-Control-Allow-Headers' 'content-type, content-length, accept-encoding, x-csrf-token, authorization, accept, origin, cache-control, x-requested-with, access-control-allow-credentials, session-tracing-id, x-b3-spanid, x-b3-traceid, x-b3-sampled, tracing-api-key, enc-id-token, x-mfa-authorize-token, businessaccountfilter, businessdepositfilter, source, primaryaccounts, intent, x-mfa-action-id, inward-currency, if-none-match, content-disposition, more-transactions, x-mfa-transaction-id, x-mfa-transaction-type, x-mfa-otp, x-mfa-otp-ref-id' always;
          add_header 'Access-Control-Max-Age' 600;
          return 204;
        }
    className: ''
    enabled: true
    hosts:
      - host: api.narratenet.com
        paths:
          - path: "/"
            pathType: ImplementationSpecific
    tls:
      - hosts:
          - api.narratenet.com
        secretName: narratenet-tls


hydra-maester:
  adminService:
    name: 'hydra-admin'
    port: 4445

hydra:
  config:
    ttl:
      access_token: 72h
      refresh_token: 720h