apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "common.names.fullname" . }}
  annotations:
    "helm.sh/hook-weight": "100"
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: 1
  template:
    spec:
      imagePullSecrets:
        - name: {{ .Values.custom.dockerRegSecret }}
      containers:
        - name: {{ include "common.names.fullname" . }}-rbac
          image: gola05/postgres-migrate:latest
          env:
            - name: ENV
              value: {{ .Values.global.env }}
            - name: DB_NAME
              value: "postgres"
            - name: DB_USER
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.secret }}
                  key: DB_HOST
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.secret }}
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.secret }}
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_DEFAULT_REGION
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.secret }}
                  key: AWS_DEFAULT_REGION
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.secret }}
                  key: DB_AWS_SECRET_KEY
          command: [ "/home/gola/migrate.sh" ]
      restartPolicy: Never